### ISSUE TITLE
El ícono de menú hace desaparecer el menú izquierdo

### ISSUE THREAD

**Issue by RHMedel** [agusrafafer/cansatu21ET#1]
Al hacer click en la hamburguesa (ícono en la esquina superior izquierda), que supone que aparecerá un menú, en realidad hace desaparecer el menú de la izquierda. 

Propongo utilizar otro símbolo para hacer desaparecer el menú y que al posicionar el cursor sobre el ícono aparezca un mensaje indicando qué acción tiene el ícono.

**Comment by agusrafafer** [comment]
Listo! corregido en la issue 2. Se podrá ver en la siguiente liberación.
