### ISSUE TITLE
No es claro cómo volver a hacer aparecer el menú de la izquierda

### ISSUE THREAD

**Issue by RHMedel** [agusrafafer/cansatu21ET#2]
Al hacer desaparecer el menú de la izquierda (haciendo click en el ícono de la hamburguesa, en la esquina superior izquierda) luego no hay forma clara de cómo hacerlo volver a aparecer (sólo tres puntos verticales en la pared izquierda de la ventana).

Propongo que aparezca algún ícono en la ventana principal para hacerlo reaparecer.

**Comment by agusrafafer** [comment]
En revisión.....

**Comment by agusrafafer** [comment]
Listo se corrigió haciendo que el icono de la hamburguesa aparezca arriba a la izquierda cuando se cierra el panel. Se podra ver en la siguiente liberación.
