### ISSUE TITLE
El buscador de archivos vuelve a directorio $HOME cada vez que se intenta cargar uno nuevo

### ISSUE THREAD

**Issue by RHMedel** [agusrafafer/cansatu21ET#4]
*No sé si esto sucede solo en mi sistema operativo*

Al intentar cargar un nuevo archivo el explorador vuelve a comenzar desde el directorio $HOME. El comportamiento ideal sería que quede almacenado el último directorio donde se encontró el archivo anterior y se comience la exploración desde ahí.

**Comment by agusrafafer** [comment]
Listo corregido. Ahora cuando se carga un nuevo archivo se abre el dialogo en el ultimo PATH seleccionado en la carga anterior.
