### ISSUE TITLE
El rótulo "Lecturas" no me parece claro

### ISSUE THREAD

**Issue by RHMedel** [agusrafafer/cansatu21ET#5]
Debajo de cada gráfico se muestran los archivos de donde se extraen los datos que se utilizan en el gráfico, bajo el rótulo "Lecturas".

No me parece que ese rótulo aporte algo o deje en claro qué está mostrando. Propongo cambiar el rótulo por "Archivos:", "Datos de archivos:" o eliminar el rótulo directamente.

**Comment by agusrafafer** [comment]
Listo, se cambio por Datos de archivos. Estar visible en el próximo release.
