### ISSUE TITLE
Los gráficos de Altitud y Temperatura muestran la Presión

### ISSUE THREAD

**Issue by RHMedel** [agusrafafer/cansatu21ET#6]
Los gráficos de Altitud y Temperatura muestran la Presión (o al menos muestra los datos así rotulados en el archivo de entrada).

En la figura de abajo la Temperatura es fija en 20°, excepto por un pico de 100 al medio°, y la Altitud es fija en 250 msm. Pero los gráficos muestran las variaciones de Presión (que varían entre 300 y 500, con una bajada de 50 al comienzo y otra al medio).

![issue6](https://user-images.githubusercontent.com/17452708/141504363-71d963e8-01d7-412f-9e07-c4eb91d6c592.png)

**Comment by agusrafafer** [comment]
Listo corregido. Era un error de tipeo en el método graficar de la clase AltitudGrafico y TemperaturaGrafico.
