### ISSUE TITLE
 [Bug] Carga de archivo nuevo persiste datos anteriores

### ISSUE THREAD

**Issue by RobertoHRomero** [agusrafafer/cansatu21ET#8]
Al realizar la carga de un archivo csv y colocar las tarjetas de cada una de las mediciones se muestran de la siguiente forma
![imagen](https://user-images.githubusercontent.com/43114984/142292895-be83f73e-ed69-440c-8462-36aec3696665.png)

![imagen](https://user-images.githubusercontent.com/43114984/142292925-fab12e8c-daae-4664-9f0a-f8d640e41e45.png)

Sin embargo, al momento de editar el mismo archivo, y cargarlo nuevamente, los gráficos permanecen, y arrastrando un nuevo ítem (temperatura al último cuadro vacío, se puede apreciar la inconsistencia.
![imagen](https://user-images.githubusercontent.com/43114984/142292955-e4d78dd1-d45c-404f-87b1-bd08dc5dd32e.png)

![imagen](https://user-images.githubusercontent.com/43114984/142292968-bef23a36-8831-4fc3-a99e-3ad44d0d092d.png)

El comportamiento deseado podría ser que una vez cargado un nuevo csv, actualice las mediciones ó en su defecto que las borre.

**Comment by RHMedel** [comment]
No es un caso de uso correcto. Se supone que los archivos contienen los datos obtenidos por el CanSat, por lo tanto no deberían ser modificados por el usuario. 

La "solución" en este caso sería no permitir cargar más de una vez el archivo, para lo cual hay que almacenar el nombre de los archivos cargados durante la sesión.

**Comment by agusrafafer** [comment]
Se soluciono permitiendo cargar en cada sesión una única vez a cada archivo seleccionado.
